### ISSUE TITLE
Ensure tree shaking is used during the build

### ISSUE THREAD

**Issue by jasongitmail** [o1-labs/snarkyjs#18]
We need to get the client bundle size _much_ smaller.

**Comment by mitschabaude** [comment]
I already poked into this a bit and want to dump my current state of thoughts:

The bundle size is dominated by the jsoo-generated code, `snarky_js_chrome.bc.js`

Sadly, this code is generated in an inherently un-treeshakeable style. Boiled down to the essentials it is of the following form:
```js
let globalObject = {};

// module 1 (corresponds to an ocaml module)
globalObject.export1OfModule1 = ...
globalObject.export2OfModule1 = ...

// module2
// ... does its things while assuming that the exports of module1 are already there, then:
globalObject.export1OfModule2 = ...
globalObject.export2OfModule2 = ...

// ... and so on ...

// final module. this module is the entry point of the jsoo build and provides the exports we need in JS
globalObject.finalExport1 = ...
globalObject.finalExport2 = ...

// put global object on the window; thus, make it all available
window.globalObject = globalObject;
```
(This is simplified of course. In actual code, each of the module parts above is wrapped in an IIFE, and these IIFEs itself seem to sometimes contain sub-globalObjects that get passed around.)

So first off, this won't be tree-shakeable because it is not an ES6 module. But for the simplified code above this is easy to fix: we just need an list of the finalExports, then we can strip away the last line `window.globalObject = globalObject;` and replace it with a real export:

```js
let {finalExport1, finalExport2, ...} = globalObject;
export {finalExport1, finalExport2, ...};
```
This seems to be what the "transpile to ES6" script of Nathan Holland does (among other things): https://gist.github.com/nholland94/641ddb34b7ca1368c80cabe1d8c90beb

However, this doesn't change the basic structure outlined above, which is multiple "modules" writing to a global object one after another. Even in ES6 form, this structure makes treeshaking impossible. This is because tree-shaking normally would work like this:
* Figure out which finalExport is actually used (imported from another file).
* Only keep the JS objects that this finalExport depends on.

However, in the code above, every finalExport depends on the globalObject. So standard tree-shaking won't elimnate anything (because it will never eliminate the globalObject, and so almost none of the other code because all the module pieces touch the globalObject).

In concrete experiments with esbuild and google closure compiler (advanced mode), neither of them can eliminate obsolete code in a structure like the above.

My conclusion so far is: There is no way to make any significant bundle size improvements by treeshaking, without going deeper into parsing and transpiling the jsoo-generated code (in a way that knows about the module dependency graph on the ocaml side, or is able to reconstruct such a graph from the jsoo code).

**Comment by mitschabaude** [comment]
Another, maybe related observation is that jsoo itself does seem to do proper dead code elimination. Thus, even if we managed to transpile the jsoo form into one that can be treeshaked, it is still not obvious that there would be large reductions of bundle size if our JS code actually needs most of the exports.

So the only "simple" strategy I can think of on the whole topic is to make multiple jsoo bundles, corresponding to multiple sets of exports that we might need.

But my higher-level conclusions on bundle size at this point are
* that the ocaml -> JS pipeline inherently produces huge bundles, because of how much basic functionality is re-created / reformulated in an ocaml-compatible way
* the only effective strategy to reduce the amount of code in the bundle is to rewrite stuff in JS, thus reduce the exports from ocaml to JS.
* I should focus on other things that improve performance first

**Comment by mitschabaude** [comment]
Bundle-size related good news is that a simple minifying step with esbuild reduces the chrome bindings `.bc.js` from 26MB to 5.5MB:

```sh
esbuild --minify snarky_js_chrome.bc.js --outfile=chrome.min.js
```

**Comment by jasongitmail** [comment]
Not actionable with current architecture due to JS of OCaml code not being tree shakeable.
