### ISSUE TITLE
Events RFC

### ISSUE THREAD

**Issue by jasongitmail** [o1-labs/snarkyjs#248]

**Comment by mitschabaude** [comment]
Events represent arbitrary information that can be passed along with a transaction.

An example use case is SmartContract's which keep some large internal state, and only store a commitment to that internal state on-chain. E.g., a Merkle tree where only the root is stored in on-chain state. Events enable to attach the full information of state changes in transactions. In the Merkle tree example, this could mean sending any Merkle leaves that are changed by the transaction as events. This means that an observer of these transactions can follow along and keep track of the full Merkle tree on their side.

For an initial iteration, we propose the add two small pieces to the API to enable events:

* a new, optional `events` field at the top level of a SmartContract, to declare _names_ and _types_ of the different events the smart contract will use
* a function `this.emitEvent(type: string, event: T)` to publish an event.

Example:

```ts
class MyContract extends SmartContract {
  events = {
    'new-leaf': Field
  }
   
  @method updateMerkleTree(leaf: Field, ...) {
    this.emitEvent('new-leaf', leaf);
    // ...
  }
}
```

In a second iteration, we also want to add a method 
```ts
this.fetchEvents(address: PublicKey, startBlock: UInt32, endBlock: UInt32)
```
which returns a list
```ts
[
  { type: 'new-leaf', event: Field(287182736) },
  { type: 'new-leaf', event: Field(214193487) },
  ...
]
```

`fetchEvents` relies on changes to the Mina / archive nodes to expose the events in an API.

Internally, every event is stored as a list of field elements as prescribed by the protocol. To distinguish different kinds of events when _receiving_ them, we essentially represent them as an enum, with
* the first of the field elements representing the type as an index 0, 1, 2.. corresponding to the alphabetical order of the event type string within the keys of the `events` object
* the rest of the field elements representing the event itself
if there is only one entry in the `events` field, as an optimization we don't store an additional index.

**Comment by MartinMinkov** [comment]
This looks good to me! 

One thing I wonder about is making the `endBlock` parameter optional and grabbing events up to the latest block published starting from `startBlock` when it's not specified. 

Also, can events track transfers or is it only on-chain state changes on a smart contract?

**Comment by mitschabaude** [comment]
Good idea of making `endBlock` optional!

> Also, can events track transfers or is it only on-chain state changes on a smart contract?
Yes, definitely! Events can be anything. One thing to note is that balance changes are already tracked by the transaction structure, they're like a built-in event already

**Comment by bkase** [comment]
What is the `UInt32` in `startBlock`? It needs to be a handle to the specific block to handle forks I think -- so a `stateHash` for example?

What are the constraints of the types for events?

```
  events = {
    'new-leaf': Field
  }
```

Is it circuitvalues? Is there a max size of the field? Is there a max length for the event string? (I suppose not since we can reconstruct it from an index?)



> In a second iteration, we also want to add a method
> 
> this.fetchEvents(address: PublicKey, startBlock: UInt32, endBlock?: UInt32)
> which returns a list
> 
> [
>   { type: 'new-leaf', event: Field(287182736) },
>   { type: 'new-leaf', event: Field(214193487) },
>  ...
> ]

Can you write the return type for `fetchEvents` -- it's a Promise right? Or does it work similarly to the state `get` where we prefetch so the actual method call doesn't have to be asynchronous? I think `fetchEvents` should be async and should be a Promise _and_ we should error if you use this inside of a smart contract where the error message says something like, "you probably want to use sequence events if your smart contract depends on recent events"

**Comment by jasongitmail** [comment]
Looks great. +1 Martin & Brandon.

```js
this.fetchEvents(address:` PublicKey, startBlock: UInt32, endBlock?: UInt32)
```

Out of scope for now, but maybe we should also accept a `name` parameter where the value could be `new-leaf` in your example, if a dev only needs specific events.

**Comment by MartinMinkov** [comment]
> What is the UInt32 in startBlock? It needs to be a handle to the specific block to handle forks I think -- so a stateHash for example?

Is there any way we can identify forks in a different way? I don't know if this functionality is in Mina, but is there a concept of a "chain id" that differentiates a forked chain? Could we write SnarkyJS in a way that can fetch from something specific like that? I think specifying a stateHash for a range of blocks you want to grab feels a bit weird.

**Comment by mitschabaude** [comment]
> What are the constraints of the types for events?

They're circuit values, i.e. `AsFieldElements<T>`. There aren't any size restrictions now, I wonder if there are size restrictions on events in the protocol? If yes, it would make sense to enforce those already on the client side.

> Can you write the return type for fetchEvents -- it's a Promise right? Or does it work similarly to the state get where we prefetch so the actual method call doesn't have to be asynchronous? I think fetchEvents should be async and should be a Promise and we should error if you use this inside of a smart contract where the error message says something like, "you probably want to use sequence events if your smart contract depends on recent events"

Thanks for bringing this up, yeah I thought it would be prefetched but now that you say it, I agree that it's a bad idea to expose this to the circuit since we won't be proving that these are in fact the events emitted to the account. With sequence events this will be possible, so it makes total sense to reserve the functionality of talking about them in the circuit to sequence events. @mrmr1993 tagging you because we talked about this but I assume you agree.

So, the new proposal is for `fetchEvents` to look like this:
```ts
// zkapp is an instance of `SmartContract`
zkapp.fetchEvents(start: ???, end?: ???): Promise<{ type: string; event: AsFieldElements<any> }[]>
```
The `address` I had before is actually not needed if it's a function on a `SmartContract` instance, which already has the address.

I don't have a good suggestion for how to specify the `start` block, because I don't know enough about the blockchain side of things. Maybe it would be easiest to just go with the "best chain" by default, so we only have to worry about specifying a point in a linear history? And possibly expose other options for advanced developers?

For example, for sequence events, I thought that it would be nice if we would only need to pass in the sequence state (= a hash identifying a point in the history of sequence events), and snarkyjs would figure out the sequence events since this state on its own. @mrmr1993 would be interested in your thoughts on this as well.

**Comment by mimoo** [comment]
looks good! I have a few questions/comments:

* what is the limit in terms of events/transaction?
* why limit an event to a single field element? It'd be nice if it was a different type that can be encoded/decoded as field elements
* why limit the query to some blocks? In Ethereum the API for events is so flexible (you can retrieve ALL events for a smart contract) that you can sort of use it as an append-only array to be consumed from outside the smart contract. So for example, imagine that you want to create a number of cities, associated to some metadata, in your dapp. The first thing you'd do in your smart contract is that you'd reach for a dictionary/hashmap. But that's impractical to query from outside the smart contract if you're trying to build the list of all cities (at least, Ethereum doesn't offer a way to do so easily). A solution is to just emit an event every time you create a city, so that a dapp/client can simply ask for all the events and construct the list from it.
