### ISSUE TITLE
Sequence Events RFC

### ISSUE THREAD

**Issue by jasongitmail** [o1-labs/snarkyjs#265]

**Comment by mitschabaude** [comment]
# Sequence Events RFC

## Part 1: Motivation

Like [events](https://github.com/o1-labs/snarkyjs/issues/248#issuecomment-1172474317), sequence events represent arbitrary information that can be passed along with a zkApp transaction. However, they have one additional feature: they are committed to on chain. We call that commitment the "sequence state"; it is a field on every zkApp account. Roughly, the sequence state is a hash (Merkle list) of the entire history of sequence events that have been posted to the account so far. Like with other account fields, you can set a precondition on the sequence state.

Being able to set this precondition means that **you can use previously emitted sequence events inside your smart contract method**. To do this, you pass in a list of sequence events and an old sequence state hash, and recompute the new (current) sequence state hash inside the circuit. Then, you set this new sequence state hash as a precondition. Thus, you prove that the sequence event list you have is actually the same list of sequence events that were posted on-chain -- in the same order -- since the old sequence state hash.

@mrmr1993 designed this as a clever mechanism to circumvent the problems with concurrent state updates in zkApps.

Let's state the problem first: Say we have a zkApp that wants to update its state in each user interaction, such that the new state depends on the old state plus the interaction inputs. (This probably applies to most zkApps!) The naive way is to directly update on-chain state in every interaction. To compute the new state, however, we have to use the current state. To _prove_ that we're really using the current state that's on-chain, we have to set a precondition on the current state. The problem: If multiple users send their transactions to the same block, without knowing from each other, they will set _the same precondition_ on the current state, and both will also update that state. Thus, every transaction after the first one has an outdated precondition on it, and is rejected.

Let's picture this with a simple example, where the `state` is just a number and the user interactions are trying to that number by 1:

```

transaction                             zkapp account after transaction
{ state: 0, newState: 1 }  ---------->  { state: 1 }
{ state: 0, newState: 1 }  -----X---->  { state: 1 }  // transaction fails, wrong state precondition

``` 
Two users sent an "increment" transaction, but the on-chain state was only incremented once!

Here's how we can solve this: Assume that we can represent our state updates as sequence events, such that the order in which those updates are applied doesn't matter (this is typically possible; more on that later). Then, we could write our smart contract so that normal users do **not** update on-chain state. They just emit a sequence event instead. No precondition, and no conflicts with other transactions!
Then, after a couple of transactions, we would have the following: An untouched on-chain state, and some emitted sequence events. Those sequence events are like "pending updates".

```

transaction                   zkapp account after transaction
{ event: INCR }  ---------->  { state: 0, events: [INCR] }
{ event: INCR }  ---------->  { state: 0, events: [INCR, INCR] }

``` 
The two user transactions are not conflicting -- both get applied, and they end up creating an account with two "increment" events.

(Note: To simplify the explanation, here I am just picturing sequence events as "events that are stored on chain". This is not precisely what happens, but is a reasonable abstraction, since we can _prove_ that certain events were stored on chain.)

The idea here is that the on-chain state is slightly lagging behind the state implied by the current list of events. To bring the on-chain state up to date with the list of events, we have another smart contract method, which we could call the "rollup method". 
What it does is:
* Prove that we have a list of sequence events that was sent to the chain (since some specific index)
* Prove that we have the current on-chain state (i.e., use a state precondition)
* Inside the circuit, apply those sequence events one after another to the old state, to produce the new state
* Set the new state to what you computed

Let's add that rollup transaction to the picture above:

```

transaction                               zkapp account after transaction
{ event: INCR }              ---------->  { state: 0, events: [INCR] }
{ event: INCR }              ---------->  { state: 0, events: [INCR, INCR] }
{ oldState: 0, newState: 2 } ---------->  { state: 2, events: [INCR, INCR] }

``` 
Now the on-chain state reflects all the updates that happened so far! 🎉 

The rough idea is that anyone would be able to send rollup transactions, so it's censorship-resistant; but probably the zkApp developer would want to set up some service that monitors the chain and makes sure to update state from time to time.

Note: If two people would send _rollup_ transactions at the same time, one of them would fail. But this doesn't matter, since no data is lost -- all the data about actual state updates is in the list of events, which can always be added without conflicts.

Another note: The pictures above may make it seem like someone could now run the rollup transaction again, using the two existing events as inputs _again_ to update the state to the corrupted value of 4. However, it's not hard to prevent this in the real implementation.

**Comment by mrmr1993** [comment]
> However, it's not hard to prevent this in the real implementation.

Explicitly: by burning an appState entry to keep track of the most-recently-applied sequence event state, and adding that into the precondition.

Great write up, thanks so much @mitschabaude!

**Comment by jasongitmail** [comment]
Thanks Gregor!

Some questions on pt 1 CC @mrmr1993 

> transaction                            zkapp account after transaction
> { event: INCR }           ---------->  { state: 0, events: [INCR] }
> { event: INCR }           ---------->  { state: 0, events: [INCR, INCR] }
> { state: 0, newState: 2 } ---------->  { state: 2, events: [INCR, INCR] }

- What happens to the first two tx's if a rollup tx does _not_ arrive by the time the next block is created? How long will they remain in the mem pool until rolled up & under what conditions would they be evicted?
- What is max # of sequence events per zkApp that the Mina node will retain in the mem pool? How does the node handle a situation where the "queue" is full, if that can occur, and another tx containing a sequence event arrives?
- Are sequence events available via Mina GraphQL API on Berkeley?
- What happens if a _rollup_ tx is received and then subsequent tx's containing sequence events are received? Will their precondition be invalid and subsequent tx's will have their precondition fail until the next block & they'd need to generate a new tx based off the new state? I suppose that depends on what precondition they choose. Or do zkApps have a way to know about this intermediate state after the rollup via the GraphQL API, implying that subsequent tx's containing sequence events and rollup tx's could be accepted into the same block?

> There are no different types of sequence events (as with events), there's just one type. This is because in the typical use case sketched above, users have to apply those events to a state one by one to compute a new state. This is hard to do in a circuit, in a static way, if the type can have any of a number of meanings. I think it's much better to just remove that headache for users by just giving them one possible event type. If they need multiple "kinds" of events, they will naturally build some kind of enum into that single type themselves, but in a way which is probably easier to deal with in a static circuit.

Makes sense.

**Comment by mimoo** [comment]
very well written! 

* my way of thinking about this: the "sequencer" (the agent that orders transactions to be rolled up) is on-chain, built as part of the zkapp. The downside, if it is one, is that the sequencer is not cleanly separated from the rollup/protocol, and perhaps expensive. 
* this translates into an overhead for every application: you need to wait twice. Once for the event to be emitted, then for the rollup to happen
* I guess no sequence events can be lost when you apply them in a rollup?

**Comment by mitschabaude** [comment]
@bkase I love the idea of using "reducer" terminology! `reducer` / `reduce` / `dispatch` will immediately get developers in the right mindset and give them something familiar. Much better than "stateUpdates" / "apply"!

Re: should we manage state -- when thinking more about the use cases for sequence events, I discovered what feels like an important use case, that isn't covered well by having a single `stateType` and a single `reduce` / "apply" function.

Namely, there's the case that
* the potential length of the history of sequence events is reasonable; say in the tens or hundreds
* there is no _single_ neat / small-ish state implied by that history which captures the history well

Example: Let's say a simplified poker zkApp creates events of the form `{player: PublicKey, bet: UInt64, round: Field}`, i.e., recording the bets that various players make during the game. And the zkApp might want to reason about things like "did player X make a bet in the current round? if yes, how large was that bet?".
If you try and capture that in a single state type, you end up with something huge, e.g. `{players: [Alice, Bob, ...], rounds: [0, 1, 2, ...], didBetInRound: [[true, false, ...], [false, ...], ...], betSizeInRound: [[100, 0, ...], [0,...], ...] }`, which is annoying and inefficient to process in a circuit. Instead, if you can make your state *specific to the current player and the current round* state, the answer of your reduce query is neat: `{didMakeBet: true, betSize: 100}`.

So, there are two points here:
* the `reduce` operation may have parameters that depend on the current run of the smart contract method. This doesn't work if it is specified before-hand, at the top level of the smart contract
* instead of storing the state returned by `reduce` either on-chain of off-chain, it might make sense to just use it within the current smart contract method run, and discard it.

Basically, the list of events themselves is the state in this use case, and it's important to reason over that list of events inside smart contracts, so we have to use sequence events instead of normal events.

As another point, there might be other smart contract methods that run an *entirely different* query on the list of events, so that the `stateType` can be mutliple different things in different `reduce` calls. In the example above, other queries could be
* in which round are we?
* which players' turn is it?
* etc

To offer such flexibility, we should only declare the event type, i.e. `actionType`, as part of the top-level `reducer`, and pass in the `(state, update) => newState` callback, as well as the `stateType` and initial state, as arguments to `reducer.reduce`.

Here's how that could look in a full example -- the counter example we already discussed.

```ts
const INCREMENT = Field.one;

class CounterZkapp_ extends SmartContract {
  reducer = SmartContract.Reducer({ actionType: Field });

  @state(Field) counter = State<Field>();
  // we also need the stateHash in on-chain state to know where in the action history we are
  @state(Field) stateHash = State<Field>();

  @method incrementCounter() {
    this.reducer.dispatch(INCREMENT);
  }

  @method rollupIncrements() {
    // get on-chain state & state hash, add preconditions for them
    let counter = this.counter.get();
    this.counter.assertEquals(counter);
    let stateHash = this.stateHash.get();
    this.stateHash.assertEquals(stateHash);

    // fetch list of actions
    let actions = this.reducer.getActions({ fromStateHash: stateHash });
    // state type
    let stateType = Field;

    // reduce takes not only the actions and initial state / hash as parameters (as before),
    // but also the stateType and reduce callback
    let { state: newCounter, stateHash: newStateHash } = reducer.reduce(
      actions,
      stateType,
      (state: Field, _action: Field) => {
        return state.add(1);
      },
      { state: counter, stateHash }
    );

    // store the new state / stateHash on chain
    this.counter.set(newCounter);
    this.stateHash.set(newStateHash);
  }
}
```

Note: In this example, we do have just one `stateType` and just one `(state, update) => newState` callback. And we do just store the reduced state on-chain. But I argue that doing this within a more flexible API is still quite straight-forward. It's a pattern for how to use `reducer` that can be easily copy-&-pasted and adapted to similar use cases. Still, we offer the full list of use cases people might have for sequence events.

For reference, this is the proposed API:

```ts
reducer = SmartContract.Reducer({ actionType: AsFieldElements<A> });
  
this.reducer.dispatch(action: A): void;

this.reducer.reduce<S>(
  actions: A[][],
  stateType: AsFieldElements<S>,
  reduce: (state: S, action: A) => S,
  initial: { state: S, stateHash: Field }
): { state: S, stateHash: Field };

// to be implement later
this.reducer.getActions({ fromStateHash?: Field, toStateHash?: Field }): A[][];
```

**Comment by mitschabaude** [comment]
@jasongitmail 
>  What happens to the first two tx's if a rollup tx does not arrive by the time the next block is created? How long will they remain in the mem pool until rolled up & under what conditions would they be evicted?
    What is max # of sequence events per zkApp that the Mina node will retain in the mem pool? How does the node handle a situation where the "queue" is full, if that can occur, and another tx containing a sequence event arrives?

Just to clarify, the first two txns modify the account state immediately. They update the "sequence state" on the account, which is a hash of all sequence events so far; so the fact that these two events happened will be forever recorded on chain, even if there is no rollup tx at all. Not sure if that answers your questions -- I think we don't really depend on the txns being in the mempool.

We do depend on being able to fetch the list of events from somewhere, to be able to rollup. We could fetch recent events from the Mina node, but they probably will get unavailable after some time (don't know the technical details). Or, we could fetch them from an archive node, where they will be available forever; or keep track of them on our own.

> Are sequence events available via Mina GraphQL API on Berkeley?

I don't think they are, currently
    
>  What happens if a rollup tx is received and then subsequent tx's containing sequence events are received? Will their precondition be invalid and subsequent tx's will have their precondition fail until the next block & they'd need to generate a new tx based off the new state? I suppose that depends on what precondition they choose. Or do zkApps have a way to know about this intermediate state after the rollup via the GraphQL API, implying that subsequent tx's containing sequence events and rollup tx's could be accepted into the same block?

Excellent question! Event-emitting txns don't have a precondition on them, so they can't become invalid. But the rollup txn has a precondition on the current sequence state, so it's valid to ask: What happens if more event-emitting txns sneak in while the rollup txn is being prepared -- will the rollup txn have an outdated precondition?

The answer is no, but requires digging into the details:

The on-chain sequence state field actually stores **sequence state hashes for the 5 most recent slots that contained sequence events**, and the sequence state precondition is accepted if it matches **any of these 5**.  

So, say that an account has the following sequence state hashes at the end of a slot: `[s1, s2, s3, s4, s5]`, and we know these were all included in a block already.
Let's say we're now in a subsequent slot, where we want to construct a rollup tx but at the same time people are submitting new events.

The first of the new events will shift the on-chain sequence state to the right, and add a new element, which represents the current slot:
```[sNEW, s1, s2, s3, s4]```
Notice that the `s5` state was thrown out, it's no longer a valid precondition.

Now, if another new event gets submitted within the same slot, it doesn't shift the states to the right again, but also updates _the first_ entry:
```[sNEW_modified, s1, s2, s3, s4]```

So the state `s1`, which represents the state at the end of the most recent block, will still remain a valid sequence state precondition **for five additional slots** after that block. Since a slot is 3 minutes, that are 15 minutes.

So, what do we do if we want to create a rollup txn?
* We look at the sequence state from the last completed block, `s1` in this case. We fetch sequence events up until that state, and rollup those events with `s1` as the precondition
* The newly submitted events, which all modify `sNEW`, don't bother us, since we are easily able to construct the rollup txn and submit it within 15 minutes, so we know `s1` will be a valid precondition
* Our transaction gets accepted, independent of how many events were submitted around the same time

It only ever makes sense to refer to the sequence event state at the end of a completed block, because that's when the order of sequence events has been fixed. It doesn't make sense to target the block that's _currently_ being constructed, and guess the order that the events in there will be applied.

@mimoo 

> I guess no sequence events can be lost when you apply them in a rollup?

Yes, if we do it like in my code example in the last post, no events can be lost -- since the smart contract method forces us to start at the `stateHash` that's stored on-chain, and which was the result of the last update

> this translates into an overhead for every application: you need to wait twice. Once for the event to be emitted, then for the rollup to happen

That's a good point. Maybe we want to encourage a framing where the pending events are also considered part of the current state, and UIs display it as such, because it's basically guaranteed that they will eventually end up in on-chain state. Not sure if that's smart though...
Otherwise it could be just "wait for two blocks instead of one" if the zkapp devloper is willing to pay for the maximally frequent rollups, or makes users pay for them in some way..

**Comment by bkase** [comment]
I really like the latest version of this 👍 . I like `actionsHash` or `actionsCommitment` with some associated doccomments that explain that it's the merkle hash of a list of actions I think?

**Comment by bkase** [comment]
> That's a good point. Maybe we want to encourage a framing where the pending events are also considered part of the current state, and UIs display it as such, because it's basically guaranteed that they will eventually end up in on-chain state. > Not sure if that's smart though...
> Otherwise it could be just "wait for two blocks instead of one" if the zkApp developer is willing to pay for maximally frequent rollups, or makes users pay for them

I like this idea and I think it's pretty safe as you said. Depends on the application, but for most the existence of a sequence event is good enough I think.
