### ISSUE TITLE
Estimate # and type (proof, signature, no signature) of parties for some use cases

### ISSUE THREAD

**Issue by jasongitmail** [o1-labs/snarkyjs#333]
- Attestation 
- Rollup (Florian)
- Recursion 
- DEX (Gregor)

**Comment by mitschabaude** [comment]
* DEX (minimal case)
  * 2 proof parties
  * 1 signature party

**Comment by Trivo25** [comment]
A rollup or potentially an application that batches payouts might involve multiple parties. 4+ parties permissioned by a proof

**Comment by Trivo25** [comment]
However, some use cases might involve writing batching contracts, or ICO contracts, that send out batches of transfers (parties)

**Comment by mitschabaude** [comment]
* Attestation -- step 1: creating the on-chain verification (minimal case)
  * 1 proof party -- the zkApp
  * 1 signature party -- the user
  
* Attestation -- step 2: proving to a 3rd party that step 1 happened
  * if the 3rd party is just a website -- no parties
  * if the 3rd party is a zkApp: 1 proof party (the zkApp), 1 signature party (the user)

**Comment by mitschabaude** [comment]
Final thoughts: I wouldn't set the most minimal possible implementations as the benchmark on any of these examples, because that would mean there is no composability, no re-usability of other zkApps. For example
* a DAO zkApp might want to see attestation that a user has completed a "proof of humanity"
* ... which is managed by another zkApp, which can provide the proof by looking up in its own sequence events / other off-chain storage
* ... for which it might rely on a third zkApp, for example, a generic zkApp
* that interaction with the DAO might also involve sending tokens, which would need invlolve the token owner zkApp as a 4th party

That's 4 proof parties for just being able to interact with that DAO. IMO, this is the kind of composability which has made Ethereum great, and which we should also strive for
