### ISSUE TITLE
Fix web version (infinite loop)

### ISSUE THREAD

**Issue by mitschabaude** [o1-labs/snarkyjs#379]
The web version of snarkyjs is reported to go into an infinite loop when compiling, cc @maht0rz @jackryanservia 

one difference to node is that for web, there's some manually written "table" of functions that are run from workers. if that table got out of date, we had the web version break sometimes
here:  https://github.com/o1-labs/snarkyjs/blob/main/src/chrome_bindings/worker_run.js

**Comment by maht0rz** [comment]
Are there any pointers as to how this can be fixed? I'd like to help

**Comment by mitschabaude** [comment]
I see two possible strategies for fixing:

1. Look at the recent history of the file bindings.js in the Mina repo, to see if functions where added / changed that got out of date with that function table mentioned above. Try to fix by updating the table
2. Try to figure out where the infinite loop happens. I usually do that with "log bisection". That probably requires to build snarkyjs from source and put print_endline statements in ocaml code (e.g. snarky_js_bindings_lib.ml in the Mina repo). Snarkyjs is built by running 'make snarkyjs' from the Mina repo

**Comment by maht0rz** [comment]
@mitschabaude is this the file you've mentioned above? I'll try comparing it manually
https://github.com/MinaProtocol/mina/blob/develop/src/lib/crypto/kimchi_bindings/js/bindings.js

**Comment by mitschabaude** [comment]
> @mitschabaude is this the file you've mentioned above? I'll try comparing it manually https://github.com/MinaProtocol/mina/blob/develop/src/lib/crypto/kimchi_bindings/js/bindings.js

Yes, @maht0rz, this is it! That file is huge so I recommend looking at its recent git history for guessing relevant changes.

**Comment by maht0rz** [comment]
Here are two profiler outputs from firefox, [before the fix](https://profiler.firefox.com/public/w0gg6xzvbjb33g08wxwfsnhe4pcqzb9kgec3dt8/calltree/?globalTrackOrder=01&implementation=js&thread=1&v=7) and [after the attempted fix](https://profiler.firefox.com/public/0j404c8bppdz7sqjp3arwgrypp93wre5g3mbxg8/calltree/?globalTrackOrder=01&implementation=js&thread=1&v=7).

I've added `undefined` since i was not able to find a coresponding WASM-ish value in the `plonk_wasm` argument.
```
caml_pasta_fp_plonk_index_create: {
        args: [
          plonk_wasm.WasmFpGateVector,
          undefined /* number */,
          undefined, // this is what i've added
          plonk_wasm.WasmFpSrs,
        ],
        res: plonk_wasm.WasmPastaFpPlonkIndex,
      },
 ```
 
 You can see the stack trace / calls changing after i've added the extra argument in the binding but i am still unable to compile my contract.

**Comment by mitschabaude** [comment]
awesome! `undefined` seems to be fine because `prev_challenges` is an integer. I think you just need to fix `caml_pasta_fq_plonk_index_create` in addition to `caml_pasta_fp_plonk_index_create` (note: `fq` vs `fp`)

**Comment by maht0rz** [comment]
It works, i will issue a PR right now! :)
