### ISSUE TITLE
Bug: toString() on Field/Bool doesn't work outside of asProver blocks

### ISSUE THREAD

**Issue by bkase** [o1-labs/snarkyjs#40]
It could work everywhere

**Comment by mitschabaude** [comment]
Partially fixed in the methods-decorator branch by using a different function to run circuits. toString should work now with the mock transaction interface -- which properly creates an as_prover block now --, but still throws during Pickles.compile where it should also work

**Comment by mitschabaude** [comment]
Will address this not by enabling `toString()` inside methods, but instead to throw a helpful error message (the former doesn't really make sense, since during compile a Field element is just an empty variable. there's no good stringification of that which wouldn't cause even more confusion) https://github.com/o1-labs/snarkyjs/issues/478

closing this one
