### ISSUE TITLE
tx.toGraphqlQuery() invalid signature when broadcasting

### ISSUE THREAD

**Issue by garethtdavies** [o1-labs/snarkyjs#440]
I am logging the GraphQL transaction generated by `Mina.transaction` i.e.

```
let tx = await Mina.transaction(
...
)
```

I would expect to be able to broadcast the resulting `tx.toGraphqlQuery()`, but doing so results in an invalid signature error.

```
"message": "Couldn't send zkApp command: (Verification_failed\n \"Invalid_signature: [B62qqPo32ULMxYW745CFdF1z8KAtxbT6Du7jnxVy2XWrBxryQeX72HH]\")",
```

The transaction sends via `await tx.send()` but not when I manually send the GraphQL mutation. Is there an extra step of signing this GraphQL request required?

**Comment by mitschabaude** [comment]
Yes, the thing is that `tx.send()` implicitly signs the transaction.

The `sign` commands that work within a `Mina.transaction` block, e.g. `zkapp.sign()`, don't really create signatures, They just mark the account update as one that has to be signed. This is because for the signature to be valid, the account update must not change after signing it.

On a finished `tx`, there is a method for finishing all the lazy signatures: `tx.sign()`. This is implicitly called by `tx.send()`.

If you want to see the graphql request with the full signatures, just explicitly call `tx.sign()` before:

```ts
let tx = await Mina.transaction(
...
);
tx.sign();
console.log(tx.toGraphqlQuery());
```

I'll document this as part of a planned docs section about the `transaction` API!

**Comment by mitschabaude** [comment]
Now that I wrote the above, I'm thinking that this should change: `Mina.transaction` could already create signatures right at the end, at least those signatures where the private keys were passed in already.

The idea for having `tx.sign()` as a separate method was that we shouldn't assume that private keys are available in the same environment where the tx was constructed. The tx construction / proof creation usually happens on a website, while the private keys would sit in some wallet. We made it so that you can leave out the private key in steps like `zkapp.sign()` and instead provide all the missing private keys at the end to `tx.sign()`:

```ts
// on website
let tx = await Mina.transaction(() => {
   // ...
   zkapp.sign();
});

// in the wallet
tx.sign([privatekey1, privateKey2, ...]);
await tx.send();
```

**Comment by shimkiv** [comment]
@mitschabaude 
- please also don't forget to rename `zkapp.sign()` to `zkapp.requireSignature()`

**Comment by garethtdavies** [comment]
Thank you for the detailed explanation. Can confirm that the `tx.sign()` step does indeed work and I can broadcast the resulting output 👍
