### ISSUE TITLE
Profile SnarkyJS CI testing

### ISSUE THREAD

**Issue by bkase** [o1-labs/snarkyjs#604]
Bonus points if CI runs always generate the speeds of the runs of the tests

And suggest plan to make improvements

**Comment by Trivo25** [comment]
## 'Benchmark' existing tests

### Option 1:


GitHub actions lets us display console output (markdown) under the [Summary tab of each PR.](https://github.com/o1-labs/snarkyjs/actions/runs/3627763351) We can slightly modify existing tests to print and temporary store output, capturing the time it takes to run each integration test and its sections, and then displaying it under the Summary tab.
This would require us to simply add a handful of helper functions to the integration tests and modify the CI workflow slightly.

![image](https://user-images.githubusercontent.com/22175568/205929970-0cb7a171-a920-4d40-b22e-e151f9a4c8eb.png)


#### Benefits: 
- simple and straightforward - no additional JS or GitHub Action library required ([such as this one](https://github.com/benchmark-action/github-action-benchmark))

### Option 2:


A second option would be to use an existing GitHub Action library, [such as this one.](https://github.com/benchmark-action/github-action-benchmark). In addition to the GitHub Action library, an additional [JavaScript library ](https://benchmarkjs.com/) would be required. 

#### Benefits: 
- ready-to-go solution with lots of custom options 

#### Disadvantages: 
- introduction of new 3rd party libraries 
- severe changes in our existing integration in order to be compatible with [BenchmarkJS](https://benchmarkjs.com/)
