### ISSUE TITLE
`this.send()` ignores send permission setting

### ISSUE THREAD

**Issue by dexterslabor** [o1-labs/snarkyjs#631]
#### Description

When using `this.send()` to send Mina from a smart contract, the `send` permission setting `Permissions.signature` (default setting) is ignored. When signing the transaction with `tx.sign([key]).send()` the transaction fails with `Update_not_permitted_app_state`.

#### Steps to reproduce the issue

```typescript
@method withdraw(address: PublicKey) {
    ...
    this.send({
      to: address,
      amount: UInt64.from(5),
    });
  }
  deploy(args: DeployArgs) {
    super.deploy(args);

    // setup permissions
    this.setPermissions({
      ...Permissions.default(),
      editState: Permissions.proofOrSignature(),
      send: Permissions.signature(),
    });
  }
...
```

#### What's the expected result?

Negative balance update for the smart contract and a positive balance update for the recipient.

#### What's the actual result?

Transaction fails with `Update_not_permitted_app_state`.

#### Additional details 

The following workaround is not desired, because it could change the `editState` permission.

```typescript
@method withdraw(address: PublicKey) {
    ...
    this.self.requireSignature();
    this.send({
      to: address,
      amount: UInt64.from(5),
    });
  }
```

Notes on the API:
As an SDK user, I would expect that `this.send()` returns an `AccountUpdate` where I could do `.requireSignature()`.

**Comment by mitschabaude** [comment]
Hey thanks for reporting! I'm a bit confused because I wouldn't think that `Update_not_permitted_app_state` is related to the use of `this.send()`, because sending doesn't update "app state". App state refers to the 8 state fields. For `this.send()` in your example, the failure I would expect is `Update_not_permitted_balance`.

However, you are describing a problem that makes sense to me, so I'm going to answer the following:
- How do we make a zkApp method authorize a payment with a signature?
- Why do we need `requireSignature()`?
- What do we do if we additionally want to change zkApp state, but we want the `editState` permission to be "proof"?

To the third question: The general model is that each account update can have just one authorization on it. Proof, signature, or none. So, if you want to apply two different updates, one with signature auth, another with proofs, then fundamentally you need to create two different account updates (for the same account).

Another thing to say is that `SmartContract` and the `@method` decorator are designed to make it easy to create account updates with proofs. A `@method` will always create a proof-authorized account update on `this.self`, except if it's explicitly overriden with `this.requireSignature()` (but then again, such an override doesn't make much sense, because you wouldn't need a `@method` to do that -- you could create your account update more explicitly, outside a method).

But what you can do, and makes sense to me the desired permissions of `editState: proof, send: signature`, is to create a second account update for the zkApp, from which you send:

```ts
@method withdraw(address: PublicKey) {
  // ... update state on `this` ...
  
  // create separate account update for sending from zkApp
  let update = AccountUpdate.create(this.address);
  update.requireSignature();
  update.send({ to: address, amount: UInt64.from(5) });
}
```

There's the question of whether you need this `send` code to be part of your `@method`. If it's in the method, it'll be included in the proof (those sub account updates we create become public input for the proof), and thus linked to whatever else you do in `withdraw` -- which might be what you want.

**Comment by mitschabaude** [comment]
closing for house keeping
