### ISSUE TITLE
RFC: Witness merging in reducer

### ISSUE THREAD

**Issue by 45930** [o1-labs/snarkyjs#659]
# Motivation
The actions/reducer(link) paradigm looks very promising as a way to handle mutli-user, async state update events.  However, it is currently not so obvious how to process these events for state which happens to be the root of a merkle tree.  The ability to merge `Witness` objects would allow developers to reduce multiple `Action`s of the form `{ witness: Witness, leafValue: Field }` into a new root hash which incorporates each separate action and does not require the full tree to be loaded in order to generate a new root.

# Current State
Imagine a scenario in which we have a zkapp with some state which represents the root hash of a merkle tree.  The merkle tree can store the current balance for each user in the zkapp.  We have 3 users, Alice, Bob, and Charlie who each wish to deposit into the app.

## Standalone Transaction
This can be accomplished without using a reducer, for instance:

```
@state root = State<Field>();

@method
deposit(user: PublicKey, amount: Field, witness: Witness) {
	// Simplified function calls
	this.root.assertEquals(this.root.get());
	this.root.assertEquals(witness.computeRoot(amount));
	user.send(this.account, amount);
	this.root.set(witness.computeRoot(amount));
}
```

The problem with this implementation is that it has a max throughput of one deposit per block (later transactions attempting to update the root will fail the second assertion.  Their witness is now out of date).  This is not acceptable for a variety of apps.  In particular, imagine some kind of "mint" or auction event which goes live at a certain time with hundreds or thousands of users.  I.e. ~20 transactions per hour might be appropriate in steady state for some apps, but there are certainly other apps with burst usage which far exceeds this rate.

## Actions/Reducer
The best available way to solve our problem is to emit actions in the deposit method, then reduce them into one state update.  This solves the problem of only allowing one transaction per block to succeed but it introduces a new problem.

### Naive Solution
```
class MerkleUpdate extends Struct({ witness: Witness, newLeaf: Field }) {};

-----------------------------------------------------

@state root = State<Field>();
@state actionsHash = State<Field>();
reducer = Reducer({ actionType: MerkleUpdate})

@method
deposit(user: PublicKey, amount: Field, witness: Witness) {
	// Simplified function calls
	this.root.assertEquals(this.root.get());
	this.root.assertEquals(witness.computeRoot(amount));
	user.send(this.account, amount);
	this.reducer.dispatch({ witness: witness, newLeaf: amount })
}

@method
reduceMerkleUpdates() {
	let root = this.root.get();
	let actionsHash = this.actionsHash.get();
	
	let { state: newRoot, actionsHash: newActionsHash } = this.reducer.reduce(
		this.reducer.getActions(actionsHash),
		MerkleUpdate,
		(state: Field, action: MerkleUpdate) => {
			return action.witness.computeRoot(action.newLeaf);
		}
	);
	
	this.root.set(newRoot);
	this.actionsHash.set(newActionsHash);
}

```

This seemingly solves the problem and would probably run, but there's an issue.  This reduction does not fail when multiple users make an update, but the root hash that ends up on the chain will not reflect the sum of all three state changes.  It will only reflect one of the state changes, whichever one happens to go last.  That's becuase the `Witness` being used in `action.witness.computeRoot(action.newLeaf);`  is the stale witness to the existing tree whose root is on chain, not to a tree which has already processed the other updates.

It turns out that in order to process all of these updates at once, we'd have to build the full tree in javascript, make the updates on that tree, then compute the new root after all of the updates are done.  This is a little weird since `MerkleTree` is not provable and can't be used as a parameter to the method.  We would need the full tree to exist outside of the scope of the method.  It also limits who is capable of running the reducer method to someone who has the enitre state stored.

# Proposal
A more elegant, and scalable, solution would be to merge witnesses to the same tree into a single witness of a new tree.

An API for this could look like:

```
BaseMerkleWitness {
	/*
	 Observes the value of this witness with the value of leaf
	 merges the paths of the other witness with the paths of this after observing the leaf
	 @returns a new witness of the related path as other, but with hashes updated based on this' observation of leaf
	*/
	merge(leaf: Field, other: BaseMerkleWitness);
}
```

And usage in a reducer could look like
```
let initialWitness = actions[0].witness;
let leaf = actions[0].leaf;
finalWitness = (state: Witness, action: MerkleUpdate) => {
	newWitness = action.witness.merge(leaf, action.witness);
	leaf = action.newLeaf;
	return newWitness;
}

this.root.set(finalWitness.computeRoot(leaf));
```

The algorithm I am imagining looks like:
- Confirm that witnesses are the same heght and not identical
	- If pass then these witnesses are mergable
- Identify the height within the path at which the witnesses differ (`h`)
	- example:
	- tree with height of 4, leaf count is 8
	- 1 and 5 are on different halves of the tree, so they differ at level 3
	- 7 and 8 are on the same half of the same half of the tree, so they differ at level 1
	- 6 and 8 would be 2
	- I believe this idea could be generalized
- calculate the hash of witness1 at the leaf up to `h` (`hash`)
- create a new witness with the same path at witness2 (`w3`)
- set the path of `w3` at index `h` to `hash`
- returrn `w3`

**Comment by mitschabaude** [comment]
Thanks for the write-up! From a technical standpoint, this checks out for me: It's a method for ensuring that the reducer can be run _without access to the Merkle tree_.

I don't yet understand what seems to be the premise: that requiring access to the Merkle tree for each user who dispatches an action is better than requiring it for the reducer.

I also don't agree that the following is a limitation / challenge:

> This is a little weird since MerkleTree is not provable and can't be used as a parameter to the method.

Actually, the whole sequence of Merkle witnesses that are used in the reducer can be computed outside the circuit, in whatever way is best, and the full list of witnesses can be given to the circuit as a method input. This is analogous to how in each individual action dispatch, the Merkle witness would be computed outside the circuit and passed in as a method input.

**Comment by Trivo25** [comment]
> I don't yet understand what seems to be the premise: that requiring access to the Merkle tree for each user who dispatches an action is better than requiring it for the reducer.

Ideally I think no one should need the original merkle tree to invoke a contract method (unless they want to do verification of the data themselves of course). If the entity that invokes the reducer method is a central entity that has access to the tree anyway I don't see an issue with using the tree within the reducer directly. 

However, using merkle proofs with the proposed solution seems to be a cleaner lightweight solution when there are multiple moving parts in the system, or it is required to parallelize work in some way or another. I think both ways are valid, depending on the scenario.

**Comment by qcomps** [comment]
Thanks for the discussion guys.  I'll try to clarify a few things then work on implementation.

@mitschabaude 

> This is a little weird since MerkleTree is not provable and can't be used as a parameter to the method.

e.g. in my personal project in which I plan to implement this solution
```
 ● Test suite failed to run

    Argument 1 of method reduceCollateralActions is not a provable type: class MerkleTree
```

To the idea of why combine witnesses vs. use the whole tree: I really like the idea of emitting actions which are inherently reducible.  Perhaps there could be service providers which just run reducers for app developers.  Perhaps users will run them for apps which they use.  Seems like a needless complication to require for all calls to this method to include the full tree as a param, even just for simplicity's sake.  For performance and speed I'm not so sure.  It seems like there's some tradeoff where a merkle tree could be too big to store locally, especially on weaker machines, but it also seems like there could be enough witnesses to merge that the time to calculate and recalculate and recalculate the new path is too long.  I guess that's a conversation to be had in the future.


@Trivo25 - not sure what you mean by "the new witness should also be fed into the circuit using Circuit.witness to not impact prover performance"

To both of you: Do you agree with the the method name `merge`?  I wonder if that's too loaded of a term, or if we keep that name if `w1` should be the proof that "survives" rather than `w2`.  Since you actually lose the witness of one of the paths, this isn't really merging 2 proofs.  It's more like updating one of the proofs.  Would take some input on the naming convention here.

**Comment by mitschabaude** [comment]
>  really like the idea of emitting actions which are inherently reducible. Perhaps there could be service providers which just run reducers for app developers.

Thanks for fleshing this out, makes sense to me now!

I agree that `Circuit.witness` should be used to bring in new witnesses by the way -- what @Trivo25 said. Or in other words: `.merge()` should happen outside the circuit

**Comment by Trivo25** [comment]
>  not sure what you mean by "the new witness should also be fed into the circuit using Circuit.witness to not impact prover performance"

Running code within `Circuit.witness` doesn't run the code as part of the proof generation, but entirely outside of the circuit/proof and only feeds a "witness" (input) back into the circuit. You can think of it as an additional input argument to your circuit.

**Comment by qcomps** [comment]
Here's a starting point:

```
/**
   * Merges in another witness which claims to be of the same tree at a different path
   * @param leaf Value to observe at the other path
   * @param other Witness which will be used to merge paths
   * @returns New MerkleWitness with the merged paths of the inputs
   */
  merge(leaf: Field, other: BaseMerkleWitness): Witness {
    const otherHeight = other.height();
    if (this.height() !== otherHeight) {
      throw Error("witnesses of different height are not mergable");
    }

    const index = Number(this.calculateIndex().toString());
    const otherIndex = Number(other.calculateIndex().toString());

    let levelWithDivergance: number = 0;
    let x = 2 ** (this.height() - 1) / 2;
    for (let i = 1; i < this.height(); i++) {
      const bothUpperHalf = index > x && otherIndex > x;
      const bothLowerHalf = index <= x && otherIndex <= x;

      if (bothUpperHalf) {
        x = x + (x / 2);
      } else if (bothLowerHalf) {
        x = x / 2;
      } else {
        levelWithDivergance = this.height() - i;
      }
    }

    // calculate hash just a bit...
    let hash = leaf;
    for (let i = 0; i < levelWithDivergance; ++i) {
      const left = Circuit.if(other.isLeft[i], hash, other.path[i]);
      const right = Circuit.if(other.isLeft[i], other.path[i], hash);
      hash = Poseidon.hash([left, right]);
    }

    const newWitness: Witness = this.isLeft.map((isLeft, i) => {
      return {
        isLeft: isLeft.toBoolean(),
        sibling: this.path[i]
      }
    });
    newWitness[levelWithDivergance].sibling = hash;
    return newWitness;
  }
}
```


```
import {
  isReady,
  Field,
  MerkleTree,
} from 'snarkyjs';

import { MerkleWitness } from '../lib/merkle_tree.js';

await isReady;

let tree = new MerkleTree(4);
class MyMerkleWitness extends MerkleWitness(4) { };

tree.setLeaf(0n, Field(10));
tree.setLeaf(1n, Field(100));
tree.setLeaf(2n, Field(1000));
tree.setLeaf(3n, Field(20));
tree.setLeaf(4n, Field(200));
tree.setLeaf(5n, Field(2000));
tree.setLeaf(6n, Field(30));

const root = tree.getRoot();

console.log(root.toString());

const w1 = new MyMerkleWitness(tree.getWitness(1n));
const w2 = new MyMerkleWitness(tree.getWitness(2n));

const w3 = new MyMerkleWitness(w1.merge(Field(150), w2));

tree.setLeaf(2n, Field(150));

console.log(tree.getRoot());
console.log(w3.calculateRoot(Field(100)));
```

**Comment by qcomps** [comment]
So the `merge` method here is decidedly not in the circuit.  Is this the pattern you had in mind?

I don't like that `MyMerkleWitness#merge` returns a different type.  That seems confusing.  If you know a way to cleanly resolve that I'd love to know.

The other question is where you recommend wrapping code in a `Circuit.witness`?  And if someone can just run any version of this function that they want, then isn't there a risk of them writing invalid data to state?  It's not clear to me why this would be allowed to operate outside the circuit.

**Comment by qcomps** [comment]
I guess to elaborate on that, the point of this api is to reduce 2 existing proofs into 1 proof.  If the conversion of 2 into 1 is not itself proved, then it seems like you get essentially a random field as output.  It's not useful.

But I wonder with a merkle witness of size 128, a proof that this was at least somewhat constrained would be that the other 127 fields in the path are equal to the starting path.  In other words, only the expected level changed.  But that's still not sufficient to say the merge was valid (if the computation is not checked as well).

There are some artifacts in my code above from attempting to do the whole thing with circuit-compatible code.  I think it's possible but would be more verbose.  So I wanted to do a temperature check and ask about it.

**Comment by mitschabaude** [comment]
@qcomps I think that we don't need to prove that we merge Merkle witnesses correctly. At a higher level, this is the process of updating a Merkle tree, inside a SNARK:

Input: an old leaf; a new leaf; an old Merkle root; a new Merkle root; a Merkle witness (= the siblings in the Merkle path)
Only _one_ of these inputs is anchored to on-chain state: the old Merkle root. The rest can be anything, it's user input.

1. Check that, when hashing the old leaf along the path given by the Merkle witness, you get the old Merkle root.
   - This proves that your old leaf was in the tree, **irrespective of what the Merkle witness is**
2. Compute the new root, using the new leaf instead of the old, but using **the same Merkle witness**
  - This proves that the new root is the correct result of transitioning from the old leaf to the new leaf
  
I think we have to perform this process in every step of the reducer. If we do that, nothing else about the Merkle witnesses has to be proved

**Comment by Comdex** [comment]
Personally, I think the above solution is not realistic and scalable under the current mina zkApp design. I think the reducer in the contract is not suitable for most applications that need to use the merkle tree. There are two main reasons (if I made a mistake, please correct me): 

First, the events or actions of each zkApp transaction has a size limit (this is also a limitation of network performance), if I am not mistaken, the current limit is 16 fields per transaction, In this way, adding leaf data to the action is already very stressful, and it is basically impossible to add a merkle witness of a common size. 

The second is to use a merkle witness of a common size in the reducer to verify and generate a new root, without other business logic, even if fewer actions are processed, it is easy to reach the upper limit of the circuit constraint size. Although we may be able to configure the number of actions processed by the reducer to be smaller to circumvent the limit (this requires sending multiple reducer transactions), we have one risk is that if our zkApp has a lot of transactions in a short period of time, the actions we process may often fail to catch up with the oldest of the 5 sequence states in the network.

For zkApp that needs to use merkle tree, I am exploring a more lightweight solution than building a complete rollup application: Actions + zkProgram.  If the transaction volume is certain and the processing time is properly controlled, I can always catch up with the sequence state that exists on the network in a transaction, if you are interested, you can take a look at my example: https://github.com/Comdex/nft-zkapp , this solution works well under the current zkApp architecture design and limitations (there may be some issues that need to be addressed that I haven't found yet 😅), I wonder if it is more valuable to provide an api like a reducer in zkProgram?

**Comment by mitschabaude** [comment]
Yes @Comdex, what you say is on point. I agree that the nft-zkapp design is what we should expose in SnarkyJS

**Comment by mitschabaude** [comment]
Yeah the actions size limit kind of kills this witness merging solution for now, I hope we can lift that limit at some point :/

**Comment by qcomps** [comment]
Dang!

Thanks for the comment @Comdex

**Comment by qcomps** [comment]
@mitschabaude 

> 
> 1. Check that, when hashing the old leaf along the path given by the Merkle witness, you get the old Merkle root.
>         This proves that your old leaf was in the tree, irrespective of what the Merkle witness is
> 2. Compute the new root, using the new leaf instead of the old, but using the same Merkle witness
>        This proves that the new root is the correct result of transitioning from the old leaf to the new leaf

I think after we merge 2 witnesses (at least as implemented here) then it no longer is the same merkle witness.  If the value at index 8 is 10 on chain and the value at index 1 is 5 - and I have 2 actions, one per index, both with the value of 15 - then after I perform one update, the other witness is invalid.  The point of this was to change the siblings in one witness so that it was a valid witness to the tree after the other update is done.  But that removes the tether to state, and you now have untrusted witnesses, which cannot produce a root which matches state.  So I still think the computation would have to be checked, which just adds more constraints...

Look at my example where we produce `w3`, a witness to index one of a tree which is different than the original one.

So it sounds like this is not viable for now.  I will read more about zkprograms.

**Comment by mitschabaude** [comment]
@qcomps to clarify, I think you should take the new (merged) witness, and with it perform the two steps of checking old root & upodating new root, for each action. so its the same witness because you do it with the same witness

**Comment by Comdex** [comment]
> Yes @Comdex, what you say is on point. I agree that the nft-zkapp design is what we should expose in SnarkyJS

To make this soluation more reliable, I think there may be two points that need to be improved urgently. 😅

One is that the circuit size limit of zkProgram needs to be configurable. Although we could batch a small number of actions by running smaller circuits and then recursively merge the state, this would consume significantly more time, even if we were using multiple threads. In my nft-zkapp example, although the logic is relatively simple, the limitation of the circuit size makes it possible to process only 15-28 Actions in one batch. We need to make the processing of actions catch up with the sequence state in the network within a limited block time. Such performance is obviously risky. Larger circuits can significantly process more Actions in one batch. Compared with recursively merging the processing results of more small batch actions, it has a time advantage.

The second is to solve the annoying "stack overflows" problem. Many times we will encounter this problem before we touch the upper limit of the circuit size. I have tested that for a simple contract, if the input parameter size of the contract method exceeds 1200 fields, there is a high probability that this problem will occur. If I'm not mistaken, this probably only handles 4-5 signatures? This problem is a roadblock for such use cases that require better performance and greater throughput.
