### ISSUE TITLE
mina-signer delegation result unexpected

### ISSUE THREAD

**Issue by psteckler** [o1-labs/snarkyjs#709]
Using mina-signer's `signStakeDelegation` produces a result that looks like a payment without the amount. It does not contain the expected fields `delegator` and `newDelegate`.

**Comment by mitschabaude** [comment]
The input/output type of `signStakeDelegation` looks as follows:
```ts
type StakeDelegation = {
  to: PublicKey;
  from: PublicKey;
  fee: UInt64;
  nonce: UInt32;
  memo?: string;
  validUntil?: UInt32;
};
```
As far as I can see, this exactly matches the GraphQL API which defines the `sendDelegation` query as follows:
https://github.com/MinaProtocol/mina/blob/f6756507ff7380a691516ce02a3cf7d9d32915ae/src/lib/mina_graphql/mina_graphql.ml#L2771-L2778

In both cases, the fields that define the delegator / newDelegate are "to" and "from". I think it's right that mina-signer matches the GraphQL API (because wallets will take a result from mina-signer and post it to the API).

@psteckler does this answer the issue? Or should we open another one to change the GraphQL API + mina-signer?

**Comment by psteckler** [comment]
I suppose it's OK, I was expecting it to match the output in `app/client_sdk/client_sdk.ml`.
