### ISSUE TITLE
Recursion / proof composition RFC

### ISSUE THREAD

**Issue by jasongitmail** [o1-labs/snarkyjs#89]

**Comment by mimoo** [comment]
> Side note: I'm not sure what's better terminology -- "public input" or "statement". "Statement" is used in the OCaml code base. I prefer statement -- it's less jargon-y and gives more intuition about what it means. However, "public input" is the well-known term, could be less ambiguous to experts. TBD

not a fan of statement because IIUC in ZK theory it often refers to the tuple `(circuit, public_input)`. I was thinking that from a developer's point of view, programming languages often have private and public/exposed functions and types and so requiring a `public` or `pub` keyword in front of everything that's not secret would be good practice (for example, even declaration of the fields of the zkapp (state) might benefit from a redundant `pub` keyword).

**Comment by mitschabaude** [comment]
Thanks for the feedback @mimoo!

> I was thinking that from a developer's point of view, programming languages often have private and public/exposed functions and types

Makes sense to me to use this analogy!

> > We can also expose the possibility to verify conditionally
>
> Is this a legitimate usecase? I was thinking: what if they forget to call verify?

I think it would be a shame not to support it, since there's no way for the developer to do conditional verification if we don't provide it, and it's already built into Pickles. We could throw an error if neither `.verify()` nor `.verifyIf()` is called, so that not verifying becomes an explicit choice and can't be caused by oversight.

> it sounds to me like it might refer to proofs created with different proof systems (other than kimchi). Maybe kimchi circuits?
Yeah, we shouldn't use this term in the API!

I'm starting to think it could be less confusing if we separated the types for `Proof` and the "proof system". In this case, we need to come up with a better term for proof system. Maybe `MultiCircuit`?

I wouldn't just call it "kimchi circuits" since what we expose is less general than that -- it's always a step + a wrap circuit, so a more precise name could be `PicklesCircuit`, but I think `MultiCircuit` may be clearer. With a separate class for the circuits we could also make it more clear that `SmartContract` is a type of `MultiCircuit`, with some extra stuff added to let it use Mina accounts etc.

> Is branch a good name?

My current favorites are `@method` and `@circuit`:

* `@method` is what we already use on `SmartContract` for declaring circuits. Reusing it could be good because its familiar, or bad/confusing because `@method` on `MultiCircuit` may not have the exact same behaviour as `@method` on `SmartContract`
* I like `@circuit` because it's obvious

**Comment by bkase** [comment]
> A serious problem with this idea is that we need some required extra step at the return statement in the @branch, so it returns a Promise.

Can’t we transform the function with the decorator to wrap it in the promise? I really like the “calling” the branches version.

agree with your reasoning for reusing `@method` , I don’t think it’s too confusing and intellisense will help people not get confused. And `@circuit`.

I like the version of Proof with the generic type parameter for the public input — this gives maximum power to consumers of the API if they want to do something crazy. Plus it keeps the knowledge of the public input shape in front when consuming one of those objects.

I don’t have any great ideas about naming for proof vs the collection of recursive proofs, but this is something we should resolve here for sure.

**Comment by mitschabaude** [comment]
I researched a bit in the direction of not using classes. Correct typing without syntax contortions would get **much** easier if we would just use a function for the `MultiCircuit`.

For example, I'm able to get this to type-check. In particular, see how the circuit becomes a prover with the same name, which returns a Promise, which holds a type that is inferred from the `publicInput` parameter (that last bit actually the hardest part).
```ts
let myCircuit = MultiCircuit({
  publicInput: UInt32,
  circuits: {
    someCircuit: {
      arguments: [Field, Bool],
      circuit(a: Field, b: Bool) {
        b.and(a.add(5).equals(10)).assertTrue();
      },
    },
  },
});

let x: Proof<UInt32> = await myCircuit.someCircuit(Field(5), Bool.true);
```
There aren't any weird hacks, lying to TS, messing with `any`, assigning something which we don't even just to make TS happy, verbosity, ... Plus, we avoid all the problems people have with decorator support...

Anyone in favor of seriously considering an approach like that? cc @bkase @mrmr1993 

(If no-one speaks up loudly, I'm going to implement this for now, because I already got the types working and the actual JS-side implementation will be quickly transferable to any other API surface)

**Comment by mitschabaude** [comment]
> Can’t we transform the function with the decorator to wrap it in the promise?

We should research that. My feeling was that you can't make TS diverge from the method signatures and prop types on a class

**Comment by mitschabaude** [comment]
We decided to go with the function-based (not class-based) approach for non-smart-contract proofs for now, as an "API experiment" to see how everyone likes this alternative. This could help inform general directions taken in our API.

Here is an example of using recursive proofs with a new primitive called `Program`. A `Program` is a collection of circuits which share the same public input. It's like a `SmartContract` but more general, and without the Mina-related functionality (like on-chain state etc). This example is fully implemented and working int [this PR](https://github.com/o1-labs/snarkyjs/pull/250).


```ts
import { SelfProof, Field, Program } from 'snarkyjs';

let MyProgram = Program({
  publicInput: Field,

  methods: {
    baseCase: {
      privateInput: [],

      method(publicInput: Field) {
        publicInput.assertEquals(Field.zero);
      },
    },

    inductiveCase: {
      privateInput: [SelfProof],

      method(publicInput: Field, earlierProof: SelfProof<Field>) {
        earlierProof.verify();
        earlierProof.publicInput.add(1).assertEquals(publicInput);
      },
    },
  },
});

console.log('compiling MyProgram...');
await MyProgram.compile();

console.log('proving base case...');
let proof = await MyProgram.baseCase(Field.zero);

console.log('proving step 1...');
proof = await MyProgram.inductiveCase(Field.one, proof);

console.log('proving step 2...');
proof = await MyProgram.inductiveCase(Field(2), proof);

console.log('ok?', proof.publicInput.toString() === '2');
```

To use merge in from the `Program` itself, you use `SelfProof`, which means you don't have to set up an extra proof class. ([Here](https://github.com/o1-labs/snarkyjs/blob/feature/recursion-2/src/examples/simple_zkapp_with_proof.ts) is another example which merges proofs into a smart contract, and also uses a proof form a different smart contract, and extends `Proof` to create the necessary proof class.)

Some smaller questions to bike-shed:

* Should it be `publicInput` or `publicInputs`?
* Should `methods` be an array, or an object?
* Should it be called `Program`?
* Should it be called `methods` and `method`?
* Should it be called `SelfProof`?
* Should we also have `OtherProof(OtherProgram)`, with the type `OtherProof<OtherPublicInput>`? This couldn't be used as easily in a SmartContract... because there we use decorators to find out the types of method arguments, and types need to exactly match names of values.

## Function vs class-based proofs

Spinning the last idea further, we could also ditch class definitions of proofs entirely. We could have:

```ts
let MyProof = Proof(() => Program);
type MyProof = Proof<Field>;
```

Currently we have the following general way of declaring a proof:
```ts
class MyProof extends Proof<Field> {
  static publicInputType = Field;
  static tag = () => Program
}
```

Or if we stick with class-based: Is "tag" a good name?

In both those examples `Program` can also be a `SmartContract`. 

The tag needs to be passed in as function so you don't have a cyclic dependency of objects when you create a custom proof for a Program that references that proof itself.
