### ISSUE TITLE
Conditional `UInt64` subtraction bug

### ISSUE THREAD

**Issue by Isaac-DeFrain** [o1-labs/snarkyjs#895]
This took me so long to pin down!
There seems to be a bug when evaluating conditional `UInt64` subtraction in SnarkyJS 0.9.8.

*Occurrences*
Ordinary conditional (throws an error when condition is false)
![image](https://user-images.githubusercontent.com/42081488/236709897-0ccb54df-8380-4612-9a22-9fbe14b54d9e.png)

`Circuit` conditional (throws errors in both cases)
![image](https://user-images.githubusercontent.com/42081488/236709887-03f04073-2af1-4da8-b3b2-6af350bf6d22.png)

![image](https://user-images.githubusercontent.com/42081488/236709842-500523d5-23cc-45e4-a39b-3e4023685531.png)

Converting the condition `toBoolean()` fixes the ordinary conditional
![image](https://user-images.githubusercontent.com/42081488/236710362-49647b84-631d-4af0-b9e1-64bc767e936a.png)
but *not* the `Circuit` conditional

**Comment by Isaac-DeFrain** [comment]
I realized that I wasn't using the latest version of `node` in those screenshots. I have confirmed these errors still occur with the latest `node v20.1.0`.

**Comment by mitschabaude** [comment]
Thanks for reporting @Isaac-DeFrain! This isn't a bug. `UInt64.sub()` asserts that the result doesn't underflow zero, and throws when it does. Since Circuit.if is a normal function call, the else case is evaluated, there's no way around that.

So, a safe subtraction of the smaller value from the larger one needs to be implemented differently. For example, you could first determine the min and max with 2 Circuit.ifs, and then do max.sub(min).

What this definitely highlights is that we should improve the error message!

**Comment by Isaac-DeFrain** [comment]
If there's a way to report the line in the smart contract method where the error occurs, that would be like a 10x improvement! When running tests with jest, you only get the line in the test where the error occurs.
